/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "gpio.h"

int main(void)
{
	  GPIO_HANDLER_LED_t 		led_r 	 = {0}, led_g = {0};
	  GPIO_HANDLER_JOYSTICK_t	joystick = {0};

	  led_r.color = LED_RED;
	  led_r.mode  = OUT;

	  led_r.color = LED_GREEN;
	  led_r.mode  = OUT;

	  joystick.mode = IN;

	  gpio_initLed(&led_r);
	  gpio_initLed(&led_g);
	  gpio_initJoystick(&joystick);

//	  uint8_t left = 0, right = 0;
//	  uint32_t up = 0, down = 0;

	  while (1)
	  {
		  gpio_readJoystick(&joystick);

	  	  if(IS_PRESSED ==joystick.input.valueLeft)
	  		gpio_switchLed(&led_r);

	  	  if(IS_PRESSED ==joystick.input.valueRight)
	  		gpio_switchLed(&led_g);
	    }

}
